name: MyMaid3
main: com.jaoafa.MyMaid3.Main
version: 2020.04.20_04.09
description: General Plugin Version 3
author: mine_book000
database: true
softdepend:
  - PermissionsEx
  - LuckPerms
  - GeoipAPI
  - dynmap
  - Votifier
  - jaoSuperAchievement
  - MinecraftJPVoteMissFiller
  - ViaVersion
  - LunaChat
commands:
  afk:
    description: >
      AFK(Away From
      Keyboard)モードをオン・オフにします。
    usage: |
      /afk: AFK(Away From Keyboard)モードをオン・オフにします。(トグル)
      /afk <Player>: 指定したPlayerのAFK情報を表示します。
    permission: mymaid.afk
  bug:
    description: 'バグ報告を行います。メッセージは公式Discordサーバの#develop_todoに送られます。'
    usage: '/bug <Message>'
    permission: mymaid.bug
  chat:
    description: >
      偽のプレイヤーをしゃべらせます。
    usage: '/chat <FakePlayer> <Message>'
    permission: mymaid.chat
  coold:
    description: >
      旧CoreProtectの情報を取得します。
    usage: |
      /coold i
      /coold l <Page>
    permission: mymaid.coold
  dedbull:
    description: >
      DedBullを飲み、暗視を付けます。または効果を消します。
    usage: /dedbull
    permission: mymaid.dedbull
  discordlink:
    description: >
      DiscordアカウントとMinecraftアカウントを紐づけます。
    usage: '/discordlink <AuthKey>'
    permission: mymaid.discordlink
  feedback:
    description: >
      フィードバックを行います。メッセージは運営チャンネルに送られます。
    usage: '/feedback <Message>'
    permission: mymaid.feedback
  g:
    description: ゲームモードを変更します。
    usage: |
      /g: クリエイティブモードならスペクテイターモードに、スペクテイターモードならクリエイティブモードに、それ以外ならクリエイティブモードに変更します。
      /g <0-3>: 指定された数値に合うゲームモードに変更します。
      /g <0-3> <Player>: 指定したプレイヤーのゲームモードを指定された数値に合うゲームモードに変更します。
    permission: mymaid.g
  getuserkey:
    description: >
      ユーザーを認証するためのキーを取得します。
    usage: /getuserkey
    permission: mymaid.getuserkey
  test:
    description: test
    usage: /test
    permission: mymaid.test
  tpalias:
    description: >
      TeleportAliasの設定をします。Admin・Moderatorのみ利用できます。
    usage: |
      /tpalias set <Target> <Replacement>: tpコマンド実行時に<Target>を<Replacement>に置き換えるよう設定します。
      /tpalias remove <Target>: tpコマンド実行時の<Target>置き換え設定を削除します。
      /tpalias list: tpコマンド実行時の置き換え設定一覧を表示します。
    permission: mymaid.tpalias
  vercheck:
    description: >
      開発部が制作しているプラグインのバージョンをチェックします。
    usage: /vercheck
    permission: mymaid.vercheck
