name: MyMaid3
main: com.jaoafa.MyMaid3.Main
version: 2019.12.31_07.52
description: General Plugin Version 3
author: mine_book000
database: true
softdepend:
  - PermissionsEx
  - LuckPerms
  - GeoipAPI
  - dynmap
  - Votifier
  - jaoSuperAchievement
  - MinecraftJPVoteMissFiller
commands:
  afk:
    description: >
      AFK(Away From
      Keyboard)モードをオン・オフにします。
    usage: |
      /afk: AFK(Away From Keyboard)モードをオン・オフにします。(トグル)
      /afk <Player>: 指定したPlayerのAFK情報を表示します。
    permission: mymaid.afk
  chat:
    description: >
      偽のプレイヤーをしゃべらせます。
    usage: '/chat <FakePlayer> <Message>'
    permission: mymaid.chat
  discordlink:
    description: >
      DiscordアカウントとMinecraftアカウントを紐づけます。
    usage: '/discordlink <AuthKey>'
    permission: mymaid.discordlink
  g:
    description: ゲームモードを変更します。
    usage: |
      /g: クリエイティブモードならスペクテイターモードに、スペクテイターモードならクリエイティブモードに、それ以外ならクリエイティブモードに変更します。
      /g <0-3>: 指定された数値に合うゲームモードに変更します。
      /g <0-3> <Player>: 指定したプレイヤーのゲームモードを指定された数値に合うゲームモードに変更します。
    permission: mymaid.g
  getuserkey:
    description: >
      ユーザーを認証するためのキーを取得します。
    usage: /getuserkey
    permission: mymaid.getuserkey
  test:
    description: test
    usage: /test
    permission: mymaid.test
